	<fieldset id="{CATEGORY}" class="demographic_category"><legend>{CATEGORY} <a class="delete_category">[delete]</a></legend>
		<a class="add_option">[Add Option]</a> 
		&emsp; | &emsp; 
		<input type="checkbox" name="use_values_only_once['{CATEGORY}']" id="use_values_only_once['{CATEGORY}']" value="true" /> 
		<label class="nostyle" for="use_values_only_once['{CATEGORY}']">Use each option only once per generated set</label>
		<hr />
	</fieldset>